const state={servers:[],selected:null},$=(q)=>document.querySelector(q);
async function api(path,options={}){const response=await fetch(path,{credentials:"same-origin",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(response.status===401){$("#login-screen").classList.remove("hidden");throw new Error("unauthorized")}if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.status===204?null:response.json()}
function text(q,v){$(q).textContent=v??"—"}function time(v){return v?new Intl.DateTimeFormat("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",second:"2-digit"}).format(new Date(v)):"никогда"}function esc(v){const n=document.createElement("span");n.textContent=v??"";return n.innerHTML}
function summary(s){text("#uptime",s.uptime_percent);text("#total",s.total);text("#online",s.online);text("#offline",s.offline);text("#unknown",s.unknown);text("#donut-total",s.total);text("#leg-online",s.online);text("#leg-offline",s.offline);text("#leg-unknown",s.unknown);text("#monitor-time",`обновлено ${time(s.generated_at)}`);const total=s.total||1,online=s.online/total*360,offline=online+s.offline/total*360;$("#donut").style.setProperty("--online",`${online}deg`);$("#donut").style.setProperty("--offline",`${offline}deg`)}
function servers(filter=""){const rows=state.servers.filter(s=>s.name.toLowerCase().includes(filter.toLowerCase()));$("#server-table").innerHTML=rows.map(s=>`<tr data-id="${s.id}"><td class="server-name">${esc(s.name)}</td><td>${esc(s.platform)}</td><td><span class="status ${s.status}"><i class="dot ${s.status==="online"?"green":s.status==="offline"?"red":"gray"}"></i> ${s.status}</span></td><td>${time(s.last_seen_at)}</td><td>${s.heartbeat_count}</td></tr>`).join("");$("#empty").classList.toggle("visible",state.servers.length===0);document.querySelectorAll("[data-id]").forEach(r=>r.onclick=()=>heartbeats(r.dataset.id))}
function draw(events){const chart=$("#chart");if(!events.length){chart.classList.add("empty");return}chart.classList.remove("empty");const values=[...events].reverse().map(e=>Math.min(e.latency_ms,30000)),max=Math.max(...values,1000),points=values.map((v,i)=>[values.length===1?450:i/(values.length-1)*900,220-v/max*190]),line=points.map(([x,y],i)=>`${i?"L":"M"}${x.toFixed(1)},${y.toFixed(1)}`).join(" ");$(".line").setAttribute("d",line);$(".area").setAttribute("d",`${line} L900,240 L0,240 Z`)}
async function heartbeats(id){state.selected=id;draw(await api(`/api/v1/servers/${id}/heartbeats`))}
async function load(){const[me,s,list]=await Promise.all([api("/api/v1/auth/me"),api("/api/v1/dashboard/summary"),api("/api/v1/servers")]);$("#login-screen").classList.add("hidden");text("#current-user",me.login);state.servers=list;summary(s);servers($("#search").value);if(state.selected)await heartbeats(state.selected)}
$("#login-form").onsubmit=async e=>{e.preventDefault();const form=new FormData(e.currentTarget);$("#login-error").textContent="";try{await api("/api/v1/auth/login",{method:"POST",body:JSON.stringify({login:form.get("login"),password:form.get("password")})});await load()}catch{$("#login-error").textContent="Неверный логин или пароль"}};
$("#logout").onclick=async()=>{await api("/api/v1/auth/logout",{method:"POST"});$("#login-screen").classList.remove("hidden")};$("#refresh").onclick=load;$("#search").oninput=e=>servers(e.target.value);load().catch(()=>{});setInterval(()=>load().catch(()=>{}),30000);
